### ISSUE TITLE
metamask show wrong balance

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#102]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. start a local devnet with ethermint
2. import the account private key into metamask
3. check the eth balance

__Expected behavior:__ the balance should be as same as configured in genesis

__Actual behavior:__ 1000000000000000000000aphoton in genesis is displayed as 2536520ETH in metamask

__Additional info:__
Result of `ethermintd q bank balances`:
```
balances:
- amount: "1000000000000000000000"
  denom: aphoton
pagination:
  next_key: null
  total: "0"
```
Result of web3 api:
```
{"jsonrpc":"2.0","id":1,"result":"0x3635c9adc5dea00000"}
```

The rpc result is correct, is it possible an issue in metamask, int overflow?
