### ISSUE TITLE
`starport serve`: address already in use

### ISSUE THREAD

**Issue by fadeev** [tharsis/ethermint#55]
`starport serve -r` is throwing an error with the current config:

```
listen on 0.0.0.0:1317: listen tcp 0.0.0.0:1317: bind: address already in use
```

Should we change `evm-rpc.address` to something other than `1317`, so it doesn't conflict with Cosmos SDK API? Like so in `config.yml`:

```
init:
  home: "$HOME/.ethermintd"
  app:
    evm-rpc:
      address: "0.0.0.0:1316"
      ws-address: "0.0.0.0:1318"
```
